version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - media-volume:/backend_app/media
      - static-volume:/backend_app/static
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - static-volume:/backend_app/static
      - media-volume:/backend_app/media
    depends_on:
      - app
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  media-volume:
  static-volume: